### PR TITLE
Gossip verify separate

### PR DESCRIPTION
**Pull request by realbigsean**
## Issue Addressed

Which issue # does this PR address?

## Proposed Changes

Please list or describe the changes introduced by this PR.

## Additional Info

Please provide any additional information. For example, future considerations
or information useful for reviewers.

### CODE REVIEW

**Comment by realbigsean** [comment]
Something I realized - we don't need to check blob slashability because we're checking headers that are *always* derived from the block that these blobs are being published with. So checking the block is enough. We were essentially checking the same block header up to 7 times. updated here: 23c8bd8fa528d73376775fd65b62b64db2bb8d66

**Comment by realbigsean** [comment]
I was also confused about why we have the second publish closure? I dumped it here and it's compiling: 3184e576a362cc8ffcbc19f5cb017ba8150e45d4

**Comment by realbigsean** [comment]
> Something I realized - we don't need to check blob slashability because we're checking headers that are _always_ derived from the block that these blobs are being published with. So checking the block is enough. We were essentially checking the same block header up to 7 times. updated here: [23c8bd8](https://github.com/michaelsproul/lighthouse/commit/23c8bd8fa528d73376775fd65b62b64db2bb8d66)

I think this might actually simplify a decent bit. Previously we thought we'd need to continue processing blobs that failed gossip on repeat blob in order to check slashability later, but now I think we should be able to just skip processing of repeat blobs altogether?

**Comment by michaelsproul** [comment]
> I was also confused about why we have the second publish closure? I dumped it here and it's compiling: https://github.com/michaelsproul/lighthouse/commit/3184e576a362cc8ffcbc19f5cb017ba8150e45d4

Nice, I had assumed that bound was necessary, but it ain't

**Comment by michaelsproul** [comment]
> I think this might actually simplify a decent bit. Previously we thought we'd need to continue processing blobs that failed gossip on repeat blob in order to check slashability later, but now I think we should be able to just skip processing of repeat blobs altogether?

This sounds right, but I am currently too tired to check properly. Can take a proper look tomorrow

**Pull request merged**
